services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      # Configure WebSocket to connect to internal server IP
      # User can override this by setting INTERNAL_SERVER_IP env variable
      - REACT_APP_WS_URL=ws://${INTERNAL_SERVER_IP:-10.251.253.1}:60006
    ports:
      - "60005:3000"  # Public access on 60005, internal on 3000
    depends_on:
      - api
    networks:
      - live-captioning-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "60006:3001"  # Expose WebSocket on internal network
    networks:
      - live-captioning-network

networks:
  live-captioning-network:
    driver: bridge
    name: live-captioning-net
