services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      # Use internal Docker service name for WebSocket connection
      - REACT_APP_WS_URL=ws://api:3001
    ports:
      - "60005:3000"  # Public access on 60005, internal on 3000
    depends_on:
      - api
    networks:
      - live-captioning-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    # No external port exposure - only accessible from within Docker network
    networks:
      - live-captioning-network

networks:
  live-captioning-network:
    driver: bridge
    name: live-captioning-net
