services:
  web:
    image: ghcr.io/ddnowicki/live_captioning-frontend:latest
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - REACT_APP_WS_URL=ws://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - live-captioning-network
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    image: ghcr.io/ddnowicki/live_captioning-backend:latest
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3001
      # These will be injected by the CI/CD pipeline from GitHub secrets
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - live-captioning-network
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  live-captioning-network:
    driver: bridge
    name: live-captioning-prod-net